### PR TITLE
Adds Makefile to support macOS icns building and installation

### PR DESCRIPTION
**Pull request by colindean**
I swear it started small! I don't like that it generates some of the files twice when it could just copy them but it runs so fast, especially when running in parallel with `-j`, that I didn't bother with further optimization.

There's probably room for a GHA config but this is enough to satisfy me.

### CODE REVIEW

**Comment by colindean** [comment]
Btw this is based on [my make-icons script](https://github.com/colindean/hejmo/blob/3c730d6723e04973468d4ab4f4dc76f87432259c/scripts/make-icons).

**Comment by colindean** [comment]
Replacing the icns file no longer works for me. Doing so causes macOS to not want to open the app. I speculate that altering the icon image is causing the signature check to fail, after which macOS prompts to trash the app as broken. I'm wondering if this can be circumvented by re-signing the app locally…

**Comment by colindean** [comment]
How to codesign with self-signed: https://stackoverflow.com/questions/27474751/how-can-i-codesign-an-app-without-being-in-the-mac-developer-program/27474942

**Comment by igrmk** [comment]
Thanks a lot for you pull request. It helped me a lot. I finally got the mac to check it. However I found that the icon looked awful on mac and I completely reworked it. Now it differs little bit from the icons for other operating systems in margins. I'm not familiar with makefiles so I've just updated the build script.

**Pull request closed without merging**
